Exclude Secure Enclave related code from CMake build (#67)
Motivation:
macOS CMake build is failing with error:

```
/Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-main/swift-certificates/Sources/X509/CertificatePrivateKey.swift:158:32: error: cannot find type 'SecureEnclave' in scope
        case secureEnclaveP256(SecureEnclave.P256.Signing.PrivateKey)
                               ^~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```

https://ci.swift.org/job/swift-package-manager-PR-macos-smoke-test/2207/console

Modifications:
Introduce compiler directive `INCLUDE_SECURE_ENCLAVE_SUPPORT` to control when
to include Secure Enclave related code. It is set in SwiftPM build (`Package.swift`)
but not CMake.